name: Build Storeman

on:
  push:
    tags:        
      - 'v[0-9]+.[0-9]+.[0-9]+-[0-9]+-sfos3.3'

env:
  RELEASE: 3.3.0.14

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Prepare
      run: mkdir RPMS

    - name: Build armv7hl
      env:
        ARCH: armv7hl
      run: bash ./scripts/build.sh

    - name: Build i486
      env:
        ARCH: i486
      run: bash ./scripts/build.sh

    - name: Create release
      run: |
        set -x
        assets=()
        for asset in RPMS/*.rpm; do
          assets+=("-a" "$asset")
        done
        tag_name="${GITHUB_REF##*/}"
        tag_name="${tag_name/%-sfos3.3}"
        if [[ "`hub release show $tag_name -f %T`" = "$tag_name" ]]
        then
          hub release edit "${assets[@]}" -m "" "$tag_name"
        else
          hub release create "${assets[@]}" -m "$tag_name" "$tag_name"
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

